[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proper MIME type configuration for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Note: Environment variables should be set in the Netlify dashboard
# These placeholders will be overridden by the values in the dashboard
[build.environment]
  VITE_SUPABASE_URL = "placeholder"
  VITE_SUPABASE_ANON_KEY = "placeholder"
  VITE_STRIPE_PUBLIC_KEY = "placeholder"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
